/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.nearfood.view;

import java.awt.CardLayout;
import java.awt.BorderLayout; // Importe o BorderLayout
import javax.swing.JPanel;
import br.com.nearfood.view.panelNovoPedido;

/**
 *
 * @author firmodev
 */
public class TelaPrincipal extends javax.swing.JFrame {
    
     // O gerenciador de layout que irá controlar a troca de painéis.
    private CardLayout cardLayout;

    /**
     * Creates new form TelaPrinciapal
     */
    public TelaPrincipal() {
        initComponents();
        
        // 1. Crie o CardLayout para o pnlPainelPrincipal que o construtor do JFrame criou
        cardLayout = new CardLayout();
        pnlPainelPrincipal.setLayout(cardLayout); // Aplique o CardLayout ao pnlPainelPrincipal
        
        // 2. Adicione os painéis de conteúdo ao pnlPainelPrincipal
        // O segundo argumento é o "nome da carta", que você usará para a troca
        pnlPainelPrincipal.add(new panelNovoPedido(), "novoPedido");
        
        // Se você tiver outros painéis (ex: tela inicial), adicione-os aqui também
        // pnlPainelPrincipal.add(new PainelInicial(), "inicial");
        
        // Mostra o painel inicial por padrão (opcional)
        // cardLayout.show(pnlPainelPrincipal, "inicial");

        // Altere a linha de pnlPainelPrincipal.setBounds para usar o BorderLayout
        // Você pode remover a linha "setBounds" e usar o layout manager do JFrame.
        // Já que você está usando a ferramenta de design do NetBeans,
        // é melhor usar o layout manager para evitar problemas de redimensionamento.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        pnlPainelDeNavegacao = new javax.swing.JPanel();
        btnPedidos = new javax.swing.JButton();
        btnNovoPedido = new javax.swing.JButton();
        btnCardapio = new javax.swing.JButton();
        btnEstoque = new javax.swing.JButton();
        btnRelatorio = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        jPanel5 = new javax.swing.JPanel();
        pnlHeader = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblProfileImage = new javax.swing.JLabel();
        pnlPainelPrincipal = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inicio");
        setBackground(new java.awt.Color(255, 255, 153));
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setPreferredSize(new java.awt.Dimension(1280, 720));
        // Mantenha o layout null aqui, já que você usou o form builder.
        // O CardLayout será aplicado apenas ao pnlPainelPrincipal.
        getContentPane().setLayout(null); 

        // ... (resto do initComponents gerado, sem modificações)

        pnlPainelDeNavegacao.setBackground(new java.awt.Color(255, 124, 38));
        pnlPainelDeNavegacao.setAlignmentY(10.0F);
        pnlPainelDeNavegacao.setLayout(new javax.swing.BoxLayout(pnlPainelDeNavegacao, javax.swing.BoxLayout.Y_AXIS));

        // ... (outros botões)

        btnNovoPedido.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        btnNovoPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/Plus Math_1.png"))); // NOI18N
        btnNovoPedido.setText("Novo Pedido");
        btnNovoPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoPedidoActionPerformed(evt);
            }
        });
        pnlPainelDeNavegacao.add(btnNovoPedido);

        // ... (resto do código)
    }// </editor-fold>                        

    private void btnPedidosActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // Se você tiver um painel para pedidos, adicione aqui
        // cardLayout.show(pnlPainelPrincipal, "pedidos");
    }                                          

    private void btnNovoPedidoActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // Altere a linha abaixo. Use pnlPainelPrincipal, que é o nome da sua variável
        // que representa o painel de conteúdo.
        cardLayout.show(pnlPainelPrincipal, "novoPedido");
    }                                             

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        //... (código padrão do main)
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnCardapio;
    private javax.swing.JButton btnEstoque;
    private javax.swing.JButton btnNovoPedido;
    private javax.swing.JButton btnPedidos;
    private javax.swing.JButton btnRelatorio;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lblProfileImage;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JPanel pnlPainelDeNavegacao;
    private javax.swing.JPanel pnlPainelPrincipal;
    // End of variables declaration                   
}