/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package br.com.nearfood.view;

/**
 *
 * @author firmodev
 */
public class PainelEstoque extends javax.swing.JPanel {

    /**
     * Creates new form PainelEstoque
     */
    public PainelEstoque() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        lblVisualizacaoDeImagem = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
        jLabel1.setText("Nome do Produto:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 24, -1, -1));

        jLabel2.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
        jLabel2.setText("Descrição:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 77, -1, -1));

        jLabel3.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
        jLabel3.setText("Preço:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 133, -1, -1));

        jLabel4.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
        jLabel4.setText("Categoria:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 183, -1, -1));

        jLabel5.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
        jLabel5.setText("Selecione Imagens:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 263, -1, -1));
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 25, 704, -1));
        add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 78, 704, -1));
        add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 134, 230, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecionar", "Refrigerantes", "Alcolicos", "Lanches", "Estrangeiro", "Caseiros" }));
        add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 184, -1, -1));

        jButton1.setBackground(new java.awt.Color(255, 255, 204));
        jButton1.setText("Selecione Arquivo");
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(239, 264, 210, -1));

        jButton2.setBackground(new java.awt.Color(102, 255, 102));
        jButton2.setText("Salvar");
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(802, 591, -1, -1));
        add(lblVisualizacaoDeImagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(619, 294, 255, 255));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JLabel lblVisualizacaoDeImagem;
    // End of variables declaration//GEN-END:variables
}
