/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package br.com.nearfood.view;

import java.awt.Container;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;

/**
 *
 * @author firmodev
 */
public class PainelEditar extends javax.swing.JPanel {

    private JLabel campoSelecionado = null; //guardando um campo

    /**
     * Creates new form PainelEditar
     */
    public PainelEditar() {
        initComponents();
         // Adiciona MouseListener a todos os labels que poderão ser editados
    JLabel[] campos = {
        lblNomeRestaurante, lblEmailRestaurante, lblTelComercial,
        lblTelRecuperacao, lblCNPJ1, lblCategoria,
        lblEstadoRestaurante, lbIsDelivery, lblHoraFuncionamento
    };

    for (JLabel lbl : campos) {
        lbl.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent e) {
                campoSelecionado = lbl; // guarda referência do label selecionado
                JOptionPane.showMessageDialog(null,
                        "Campo selecionado: " + lbl.getText());
            }
        });
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        lblIconeRestaurante = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblNomeRestaurante = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblEmailRestaurante = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblTelComercial = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblTelRecuperacao = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblCNPJ1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblCategoria = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblEstadoRestaurante = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lbIsDelivery = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lblHoraFuncionamento = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescricaoRestaurante = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        btnEditar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Fira Sans", 0, 16)); // NOI18N
        jLabel5.setText("Icone do Restaurante:");

        lblIconeRestaurante.setText("jLabel8");

        jLabel2.setFont(new java.awt.Font("Fira Sans", 0, 16)); // NOI18N
        jLabel2.setText("Nome do Restaurante: ");

        lblNomeRestaurante.setText("Restaurante Bom Sabor");

        jLabel1.setFont(new java.awt.Font("Fira Sans", 0, 16)); // NOI18N
        jLabel1.setText("Email: ");

        lblEmailRestaurante.setText("teste.de.email@teste.com");

        jLabel4.setFont(new java.awt.Font("Fira Sans", 0, 16)); // NOI18N
        jLabel4.setText("Telefone comercial: ");

        lblTelComercial.setText("11 986658441");

        jLabel3.setFont(new java.awt.Font("Fira Sans", 0, 16)); // NOI18N
        jLabel3.setText("Telefone de recuperação: ");

        lblTelRecuperacao.setText("jLabel6");

        jLabel6.setFont(new java.awt.Font("Fira Sans", 0, 16)); // NOI18N
        jLabel6.setText("CNPJ:");

        lblCNPJ1.setText("jLabel6");

        jLabel10.setFont(new java.awt.Font("Fira Sans", 0, 16)); // NOI18N
        jLabel10.setText("Categoria do Restaurante:");

        lblCategoria.setText("jLabel6");

        jLabel11.setFont(new java.awt.Font("Fira Sans", 0, 16)); // NOI18N
        jLabel11.setText("UF do Restaurante: ");

        lblEstadoRestaurante.setText("jLabel7");

        jLabel12.setFont(new java.awt.Font("Fira Sans", 0, 16)); // NOI18N
        jLabel12.setText("Delivery:");

        lbIsDelivery.setText("jLabel7");

        jLabel13.setFont(new java.awt.Font("Fira Sans", 0, 16)); // NOI18N
        jLabel13.setText("Horario de funcionamento:");

        lblHoraFuncionamento.setText("jLabel7");

        jLabel9.setFont(new java.awt.Font("Fira Sans", 0, 16)); // NOI18N
        jLabel9.setText("Descrição:");

        txtDescricaoRestaurante.setColumns(20);
        txtDescricaoRestaurante.setRows(5);
        jScrollPane1.setViewportView(txtDescricaoRestaurante);

        jLabel8.setFont(new java.awt.Font("Fira Sans", 0, 10)); // NOI18N
        jLabel8.setText("Ultima mudança feita: ");

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(571, Short.MAX_VALUE)
                .addComponent(btnEditar)
                .addGap(29, 29, 29))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(20, 20, 20)
                            .addComponent(lblIconeRestaurante))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(20, 20, 20)
                            .addComponent(lblTelComercial, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(20, 20, 20)
                            .addComponent(lblTelRecuperacao))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addGap(22, 22, 22)
                            .addComponent(lblCNPJ1))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(lblCategoria))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(lblEstadoRestaurante))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(lbIsDelivery))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(20, 20, 20)
                            .addComponent(lblHoraFuncionamento))
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(410, 410, 410)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(20, 20, 20)
                                .addComponent(lblEmailRestaurante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(23, 23, 23)
                                .addComponent(lblNomeRestaurante, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(441, Short.MAX_VALUE)
                .addComponent(btnEditar)
                .addGap(198, 198, 198))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel5)
                        .addComponent(lblIconeRestaurante))
                    .addGap(60, 60, 60)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2)
                        .addComponent(lblNomeRestaurante))
                    .addGap(20, 20, 20)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1)
                        .addComponent(lblEmailRestaurante))
                    .addGap(20, 20, 20)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel4)
                        .addComponent(lblTelComercial))
                    .addGap(10, 10, 10)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3)
                        .addComponent(lblTelRecuperacao))
                    .addGap(20, 20, 20)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel6)
                        .addComponent(lblCNPJ1))
                    .addGap(20, 20, 20)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel10)
                        .addComponent(lblCategoria))
                    .addGap(30, 30, 30)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel11)
                        .addComponent(lblEstadoRestaurante))
                    .addGap(20, 20, 20)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel12)
                        .addComponent(lbIsDelivery))
                    .addGap(20, 20, 20)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel13)
                        .addComponent(lblHoraFuncionamento))
                    .addGap(30, 30, 30)
                    .addComponent(jLabel9)
                    .addGap(10, 10, 10)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:

        editarCampoSelecionado(); //chamando metodo
    }//GEN-LAST:event_btnEditarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbIsDelivery;
    private javax.swing.JLabel lblCNPJ1;
    private javax.swing.JLabel lblCategoria;
    private javax.swing.JLabel lblEmailRestaurante;
    private javax.swing.JLabel lblEstadoRestaurante;
    private javax.swing.JLabel lblHoraFuncionamento;
    private javax.swing.JLabel lblIconeRestaurante;
    private javax.swing.JLabel lblNomeRestaurante;
    private javax.swing.JLabel lblTelComercial;
    private javax.swing.JLabel lblTelRecuperacao;
    private javax.swing.JTextArea txtDescricaoRestaurante;
    // End of variables declaration//GEN-END:variables

    private void editarCampoSelecionado() {
        if (campoSelecionado == null) {
            JOptionPane.showMessageDialog(this, "Selecione um campo antes de editar!");
            return;
        }

        String textoAtual = campoSelecionado.getText();
        JTextField campoEdicao = new JTextField(textoAtual, 20);

        // Substitui o JLabel pelo JTextField no mesmo container
        Container parent = campoSelecionado.getParent();
        int index = -1;
        for (int i = 0; i < parent.getComponentCount(); i++) {
            if (parent.getComponent(i) == campoSelecionado) {
                index = i;
                break;
            }
        }

        if (index != -1) {
            parent.remove(index);
            parent.add(campoEdicao, index);
            parent.revalidate();
            parent.repaint();

            final int posicao = index; // precisei declarar como um final para estar acessivel no botão

            campoEdicao.addActionListener(e -> {
                String novoTexto = campoEdicao.getText();
                JLabel novoLabel = new JLabel(novoTexto);
                parent.remove(campoEdicao);
                parent.add(novoLabel, posicao);
                parent.revalidate();
                parent.repaint();
                campoSelecionado = null;

                // Permite clicar novamente para editar
                novoLabel.addMouseListener(new MouseAdapter() {
                    @Override
                    public void mouseClicked(MouseEvent e2) {
                        campoSelecionado = novoLabel;
                        JOptionPane.showMessageDialog(parent, "Campo selecionado novamente!");
                    }
                });
            });
            
            
        }
        
        
    }
    
    
    //  função para debugar
    public static void main(String[] args) {
        SwingUtilities.invokeLater(() -> new PainelEditar().setVisible(true));
    }
}
