
package br.com.nearfood.view;
import javax.swing.*;

import br.com.nearfood.controller.LoginController;
import br.com.nearfood.model.Usuario;
import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;


public class TelaLogin extends javax.swing.JFrame {

    /**
     * Creates new form TelaLogin
     */
    
    private final LoginController loginController;
    
    
    public TelaLogin() {
        initComponents();
        setTitle("Login");
        setSize(500, 450);
        loginController = new LoginController(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtSenha = new javax.swing.JPasswordField();
        btnBotaoEntrar = new javax.swing.JButton();
        lblEsqueceuSenha = new javax.swing.JLabel();
        lblFazerCadastro = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        txtMensagem = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(494, 400));
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Email:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(54, 6, 50, 20);
        jPanel1.add(txtEmail);
        txtEmail.setBounds(54, 38, 389, 30);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Senha:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(54, 86, 50, 20);

        txtSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSenhaActionPerformed(evt);
            }
        });
        jPanel1.add(txtSenha);
        txtSenha.setBounds(54, 118, 389, 30);

        btnBotaoEntrar.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        btnBotaoEntrar.setText("Entrar");
        btnBotaoEntrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBotaoEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBotaoEntrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnBotaoEntrar);
        btnBotaoEntrar.setBounds(365, 209, 74, 24);

        lblEsqueceuSenha.setFont(new java.awt.Font("Liberation Sans", 2, 13)); // NOI18N
        lblEsqueceuSenha.setText("<html> \t<U>  \tEsqueceu sua senha? \t</U>  ");
        lblEsqueceuSenha.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblEsqueceuSenha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblEsqueceuSenhaMouseClicked(evt);
            }
        });
        jPanel1.add(lblEsqueceuSenha);
        lblEsqueceuSenha.setBounds(54, 154, 133, 16);
        lblEsqueceuSenha.getAccessibleContext().setAccessibleName("<html>\n\t<u>Esqueceu sua senha?</u>\n\n</html>");

        lblFazerCadastro.setFont(new java.awt.Font("Liberation Sans", 2, 13)); // NOI18N
        lblFazerCadastro.setText("Não tem uma conta? Faça o Cadastro");
        lblFazerCadastro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblFazerCadastro.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                lblFazerCadastroAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        lblFazerCadastro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFazerCadastroMouseClicked(evt);
            }
        });
        jPanel1.add(lblFazerCadastro);
        lblFazerCadastro.setBounds(205, 154, 221, 16);

        jCheckBox1.setText("Aceitar Termos de Uso");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox1);
        jCheckBox1.setBounds(50, 180, 172, 22);
        jPanel1.add(txtMensagem);
        txtMensagem.setBounds(60, 210, 280, 0);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 140, 495, 251);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel3);
        jLabel3.setBounds(209, 398, 0, 0);

        jLabel5.setFont(new java.awt.Font("Noto Serif CJK HK", 0, 24)); // NOI18N
        jLabel5.setText("Near Food");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(260, 100, 130, 33);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/traced-logo-nearfood.png.png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(160, 70, 100, 90);

        jPanel3.setBackground(new java.awt.Color(255, 153, 51));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel7.setText("BEM VINDO!");
        jPanel3.add(jLabel7);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 0, 500, 50);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSenhaActionPerformed
        // TODO add your handling code here:
        //onde o usuario digitara sua senha
        
        
        
    }//GEN-LAST:event_txtSenhaActionPerformed

    private void btnBotaoEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBotaoEntrarActionPerformed
       //funções ao clicar no botão "entrar" na tela de login
       
       
         Usuario user = new Usuario();
        
        //USUÁRIO E SENHA
        String email = txtEmail.getText();
        String senha = txtSenha.getText();
        
        try {
            if (user.login(email, senha)){
                //String nome = user.getNome(email);
                TelaInicio home = new TelaInicio();
                home.setVisible(true);
                this.dispose();
            }
            else{
                txtMensagem.setForeground(Color.RED);
                txtMensagem.setText("Usuário ou senha incorretos!");
            } 
        } catch (SQLException ex) {
            Logger.getLogger(TelaLogin.class.getName()).log(Level.SEVERE, null, ex);
        }
       
       
         
        
    }//GEN-LAST:event_btnBotaoEntrarActionPerformed

    private void lblFazerCadastroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFazerCadastroMouseClicked
        // TODO add your handling code here:
        
       loginController.cadastrarUsuario();
        
    }//GEN-LAST:event_lblFazerCadastroMouseClicked

    private void lblEsqueceuSenhaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEsqueceuSenhaMouseClicked
        // TODO add your handling code here:
        
        loginController.esqueceuSenha();
    }//GEN-LAST:event_lblEsqueceuSenhaMouseClicked

    private void lblFazerCadastroAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_lblFazerCadastroAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_lblFazerCadastroAncestorAdded

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBotaoEntrar;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblEsqueceuSenha;
    private javax.swing.JLabel lblFazerCadastro;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JLabel txtMensagem;
    private javax.swing.JPasswordField txtSenha;
    // End of variables declaration//GEN-END:variables
}
