/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.nearfood.view;

import java.awt.CardLayout;
import javax.swing.JPanel;
import br.com.nearfood.view.panelNovoPedido;

/**
 *
 * @author firmodev
 */
public class TelaPrincipal extends javax.swing.JFrame {
    
     // O JPanel principal que irá conter os outros painéis.

    // O gerenciador de layout que irá controlar a troca de painéis.
    private CardLayout cardLayout;
    

    /**
     * Creates new form TelaPrinciapal
     */
    public TelaPrincipal() {
        initComponents();
        //setSize(1280, 720);
        cardLayout = new CardLayout();
        pnlPainelPrincipal.setLayout(cardLayout); // Aplique o CardLayout ao pnlPainelPrincipal
        
       pnlPainelPrincipal.add(new panelNovoPedido(), "novoPedido");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPainelDeNavegacao = new javax.swing.JPanel();
        btnPedidos = new javax.swing.JButton();
        btnNovoPedido = new javax.swing.JButton();
        btnCardapio = new javax.swing.JButton();
        btnEstoque = new javax.swing.JButton();
        btnRelatorio = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        jPanel5 = new javax.swing.JPanel();
        pnlHeader = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblProfileImage = new javax.swing.JLabel();
        pnlPainelPrincipal = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inicio");
        setBackground(new java.awt.Color(255, 255, 153));
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setPreferredSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(null);

        pnlPainelDeNavegacao.setBackground(new java.awt.Color(255, 124, 38));
        pnlPainelDeNavegacao.setAlignmentY(10.0F);
        pnlPainelDeNavegacao.setLayout(new javax.swing.BoxLayout(pnlPainelDeNavegacao, javax.swing.BoxLayout.Y_AXIS));

        btnPedidos.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        btnPedidos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/Purchase Order.png"))); // NOI18N
        btnPedidos.setText("Pedidos");
        btnPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPedidosActionPerformed(evt);
            }
        });
        pnlPainelDeNavegacao.add(btnPedidos);

        btnNovoPedido.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        btnNovoPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/Plus Math_1.png"))); // NOI18N
        btnNovoPedido.setText("Novo Pedido");
        btnNovoPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoPedidoActionPerformed(evt);
            }
        });
        pnlPainelDeNavegacao.add(btnNovoPedido);

        btnCardapio.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        btnCardapio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/Menu.png"))); // NOI18N
        btnCardapio.setText("Cardapio");
        pnlPainelDeNavegacao.add(btnCardapio);

        btnEstoque.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        btnEstoque.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/Box.png"))); // NOI18N
        btnEstoque.setText("Estoque");
        pnlPainelDeNavegacao.add(btnEstoque);

        btnRelatorio.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        btnRelatorio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/Bar Chart.png"))); // NOI18N
        btnRelatorio.setText("Relatório");
        pnlPainelDeNavegacao.add(btnRelatorio);

        getContentPane().add(pnlPainelDeNavegacao);
        pnlPainelDeNavegacao.setBounds(0, 93, 200, 630);
        getContentPane().add(jLabel5);
        jLabel5.setBounds(330, 170, 0, 0);
        getContentPane().add(filler1);
        filler1.setBounds(710, 390, 0, 0);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel5);
        jPanel5.setBounds(1020, 240, 130, 40);

        pnlHeader.setBackground(new java.awt.Color(255, 204, 153));

        jLabel1.setFont(new java.awt.Font("Inter", 1, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/traced-logo-nearfood.png.png"))); // NOI18N
        jLabel1.setText("NearFood");

        lblProfileImage.setText("Icon-profile");

        javax.swing.GroupLayout pnlHeaderLayout = new javax.swing.GroupLayout(pnlHeader);
        pnlHeader.setLayout(pnlHeaderLayout);
        pnlHeaderLayout.setHorizontalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeaderLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 921, Short.MAX_VALUE)
                .addComponent(lblProfileImage)
                .addGap(28, 28, 28))
        );
        pnlHeaderLayout.setVerticalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHeaderLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(pnlHeaderLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(lblProfileImage)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(pnlHeader);
        pnlHeader.setBounds(0, 0, 1200, 90);

        javax.swing.GroupLayout pnlPainelPrincipalLayout = new javax.swing.GroupLayout(pnlPainelPrincipal);
        pnlPainelPrincipal.setLayout(pnlPainelPrincipalLayout);
        pnlPainelPrincipalLayout.setHorizontalGroup(
            pnlPainelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 970, Short.MAX_VALUE)
        );
        pnlPainelPrincipalLayout.setVerticalGroup(
            pnlPainelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 620, Short.MAX_VALUE)
        );

        getContentPane().add(pnlPainelPrincipal);
        pnlPainelPrincipal.setBounds(210, 90, 970, 620);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPedidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPedidosActionPerformed

    private void btnNovoPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoPedidoActionPerformed
        // quando o usuario clicar nesse botão, aparecerá o panelNovoPedido
        pnlPainelPrincipal.add(btnNovoPedido);
        
    }//GEN-LAST:event_btnNovoPedidoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
                
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCardapio;
    private javax.swing.JButton btnEstoque;
    private javax.swing.JButton btnNovoPedido;
    private javax.swing.JButton btnPedidos;
    private javax.swing.JButton btnRelatorio;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lblProfileImage;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JPanel pnlPainelDeNavegacao;
    private javax.swing.JPanel pnlPainelPrincipal;
    // End of variables declaration//GEN-END:variables
}
