/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.nearfood.view;

/**
 *
 * @author firmodev
 */
public class TelaVender extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrinciapal
     */
    public TelaVender() {
        initComponents();
        setSize(1280, 720);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnPainelDeFuncionalidades = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        jPanel4 = new javax.swing.JPanel();
        btnInicio = new javax.swing.JButton();
        btnVender = new javax.swing.JButton();
        btnProdutos = new javax.swing.JButton();
        btnClientes = new javax.swing.JButton();
        btnHistorico = new javax.swing.JButton();
        btnUsuarios = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        lblProfileImage = new javax.swing.JLabel();
        jpnPainelFuncionalidades2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().setLayout(null);

        jpnPainelDeFuncionalidades.setBackground(new java.awt.Color(255, 124, 38));
        jpnPainelDeFuncionalidades.setAlignmentY(10.0F);
        jpnPainelDeFuncionalidades.setName(""); // NOI18N
        jpnPainelDeFuncionalidades.setLayout(new javax.swing.BoxLayout(jpnPainelDeFuncionalidades, javax.swing.BoxLayout.Y_AXIS));

        jButton5.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
        jButton5.setText("Novo Pedido");
        jpnPainelDeFuncionalidades.add(jButton5);

        jButton6.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
        jButton6.setText("Pedidos em Aberto");
        jpnPainelDeFuncionalidades.add(jButton6);

        jButton7.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
        jButton7.setText("Pagamentos");
        jpnPainelDeFuncionalidades.add(jButton7);

        jButton8.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
        jButton8.setText("Cancelamentos");
        jpnPainelDeFuncionalidades.add(jButton8);

        getContentPane().add(jpnPainelDeFuncionalidades);
        jpnPainelDeFuncionalidades.setBounds(0, 43, 200, 230);
        getContentPane().add(jLabel5);
        jLabel5.setBounds(330, 170, 0, 0);
        getContentPane().add(filler1);
        filler1.setBounds(710, 390, 0, 0);

        btnInicio.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
        btnInicio.setText("Inicio");
        jPanel4.add(btnInicio);

        btnVender.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
        btnVender.setText("Vender");
        jPanel4.add(btnVender);

        btnProdutos.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
        btnProdutos.setText("Produtos");
        jPanel4.add(btnProdutos);

        btnClientes.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
        btnClientes.setText("Clientes");
        jPanel4.add(btnClientes);

        btnHistorico.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
        btnHistorico.setText("Histórico");
        jPanel4.add(btnHistorico);

        btnUsuarios.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
        btnUsuarios.setText("Usuarios");
        jPanel4.add(btnUsuarios);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(0, 0, 620, 39);

        lblProfileImage.setText("Icon-profile");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(206, Short.MAX_VALUE)
                .addComponent(lblProfileImage)
                .addGap(19, 19, 19))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblProfileImage)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel5);
        jPanel5.setBounds(980, 0, 300, 30);

        jpnPainelFuncionalidades2.setBackground(new java.awt.Color(255, 124, 38));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/Gears.png"))); // NOI18N
        jButton2.setText("Configuração");

        javax.swing.GroupLayout jpnPainelFuncionalidades2Layout = new javax.swing.GroupLayout(jpnPainelFuncionalidades2);
        jpnPainelFuncionalidades2.setLayout(jpnPainelFuncionalidades2Layout);
        jpnPainelFuncionalidades2Layout.setHorizontalGroup(
            jpnPainelFuncionalidades2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnPainelFuncionalidades2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jButton2)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jpnPainelFuncionalidades2Layout.setVerticalGroup(
            jpnPainelFuncionalidades2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnPainelFuncionalidades2Layout.createSequentialGroup()
                .addContainerGap(381, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(20, 20, 20))
        );

        getContentPane().add(jpnPainelFuncionalidades2);
        jpnPainelFuncionalidades2.setBounds(0, 270, 200, 450);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaVender.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaVender.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaVender.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaVender.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaVender().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClientes;
    private javax.swing.JButton btnHistorico;
    private javax.swing.JButton btnInicio;
    private javax.swing.JButton btnProdutos;
    private javax.swing.JButton btnUsuarios;
    private javax.swing.JButton btnVender;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jpnPainelDeFuncionalidades;
    private javax.swing.JPanel jpnPainelFuncionalidades2;
    private javax.swing.JLabel lblProfileImage;
    // End of variables declaration//GEN-END:variables
}
