# Generated by Django 5.2.7 on 2025-12-07 23:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('icone', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'db_table': 'tbl_Categoria',
            },
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Promocao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('desconto_percentual', models.IntegerField()),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'tbl_Promocoes',
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=100)),
                ('hora_funcionamento', models.CharField(max_length=50)),
                ('delivery', models.BooleanField(default=False)),
                ('telefone', models.CharField(max_length=30)),
                ('website', models.URLField(blank=True, max_length=255, null=True)),
                ('avaliacao', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tbl_Restaurantes',
            },
        ),
    ]
