# Generated by Django 5.2.7 on 2025-12-07 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurantes', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='recomendado',
            field=models.BooleanField(default=False),
        ),
    ]
