# Generated by Django 5.2.7 on 2025-12-14 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurantes', '0003_restaurant_recomendado'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='restaurantes/'),
        ),
    ]
