# Generated by Django 5.2.7 on 2025-12-17 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurantes', '0005_itemcardapio'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='cep',
            field=models.IntegerField(blank=True, max_length=9, null=True),
        ),
    ]
