# Generated by Django 5.2.7 on 2025-12-17 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurantes', '0006_restaurant_cep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='cep',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
