# Generated by Django 5.2.7 on 2025-12-18 18:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurantes', '0008_avaliacao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='favoritos',
            field=models.ManyToManyField(blank=True, related_name='restaurantes_favoritos', to=settings.AUTH_USER_MODEL),
        ),
    ]
