# Generated by Django 5.2.7 on 2025-11-03 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrador',
            name='cnpj',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='Os grupos aos quais este usuário pertence.', related_name='usuario_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo',
            field=models.CharField(choices=[('cliente', 'Cliente'), ('admin', 'Administrador'), ('root', 'Root')], default='cliente', max_length=20),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Permissões específicas deste usuário.', related_name='usuario_permission_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
