# Generated by Django 5.2.7 on 2025-10-06 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo',
            field=models.CharField(choices=[('cliente', 'Cliente'), ('admin', 'Administrador')], max_length=20),
        ),
    ]
