# Generated by Django 5.2.7 on 2025-12-14 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurantes', '0004_restaurant_imagem'),
        ('Usuarios', '0002_tokenresetsenha'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='favoritos',
            field=models.ManyToManyField(blank=True, related_name='favoritado_por', to='Restaurantes.restaurant'),
        ),
    ]
