# Generated by Django 5.2.7 on 2025-11-03 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0002_administrador_cnpj_alter_usuario_groups_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='cpf',
        ),
    ]
