# Generated by Django 5.2.7 on 2025-10-07 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0002_alter_usuario_tipo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fornecedor',
        ),
    ]
