# Generated by Django 5.2.7 on 2025-12-14 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0003_usuario_favoritos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dono',
            name='cnpj',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
    ]
