/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.nearfood.views;

import br.com.nearfood.service.LoginService;
import javax.swing.JOptionPane;

/**
 *
 * @author firmodev
 */
public class TelaLoginNew extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaLoginNew.class.getName());

    /**
     * Creates new form TelaLoginNew
     */
    public TelaLoginNew() {
        initComponents();
       this.setExtendedState(java.awt.Frame.MAXIMIZED_BOTH);
        
        // Ajuste para o fundo preencher a tela
        this.setLayout(new java.awt.BorderLayout());
        this.add(jblBackground, java.awt.BorderLayout.CENTER);

        // Lógica para centralizar o jlbGrid quando a tela for redimensionada
        this.addComponentListener(new java.awt.event.ComponentAdapter() {
            @Override
            public void componentResized(java.awt.event.ComponentEvent evt) {
                // Calcula o centro
                int x = (getWidth() - jlbGrid.getWidth()) / 2;
                int y = (getHeight() - jlbGrid.getHeight()) / 2;
                jlbGrid.setLocation(x, y);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jblBackground = new javax.swing.JPanel();
        jlbGrid = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblEsqueceuSenha = new javax.swing.JLabel();
        txtUserInput = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        lblCriarConta = new javax.swing.JLabel();
        chkManterLogin = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        txtPswdInput = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jblBackground.setBackground(new java.awt.Color(255, 153, 51));
        jblBackground.setPreferredSize(new java.awt.Dimension(1366, 768));
        jblBackground.setLayout(null);

        jlbGrid.setBackground(new java.awt.Color(255, 255, 255));
        jlbGrid.setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logos/Logo Nearfood__extenso.png"))); // NOI18N
        jlbGrid.add(jLabel2);
        jLabel2.setBounds(720, 90, 520, 110);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Imagem-login.png"))); // NOI18N
        jlbGrid.add(jLabel3);
        jLabel3.setBounds(0, 0, 640, 650);

        jLabel1.setFont(new java.awt.Font("Poppins SemiBold", 0, 26)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Olá, seja muito bem-vindo ao");
        jlbGrid.add(jLabel1);
        jLabel1.setBounds(760, 20, 420, 30);

        jLabel4.setFont(new java.awt.Font("Lato", 0, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Senha:");
        jlbGrid.add(jLabel4);
        jLabel4.setBounds(740, 400, 80, 25);

        lblEsqueceuSenha.setFont(new java.awt.Font("Lato", 0, 14)); // NOI18N
        lblEsqueceuSenha.setForeground(new java.awt.Color(0, 0, 0));
        lblEsqueceuSenha.setText("Esqueceu sua senha?");
        lblEsqueceuSenha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblEsqueceuSenhaMouseClicked(evt);
            }
        });
        jlbGrid.add(lblEsqueceuSenha);
        lblEsqueceuSenha.setBounds(1050, 480, 130, 17);

        txtUserInput.setBackground(new java.awt.Color(255, 255, 255));
        txtUserInput.setForeground(new java.awt.Color(51, 51, 51));
        jlbGrid.add(txtUserInput);
        txtUserInput.setBounds(740, 300, 440, 50);

        jLabel6.setFont(new java.awt.Font("Lato", 0, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Usuario:");
        jlbGrid.add(jLabel6);
        jLabel6.setBounds(740, 270, 90, 25);

        lblCriarConta.setFont(new java.awt.Font("Lato", 0, 14)); // NOI18N
        lblCriarConta.setForeground(new java.awt.Color(0, 0, 0));
        lblCriarConta.setText("Não tem login? Crie sua conta");
        lblCriarConta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCriarContaMouseClicked(evt);
            }
        });
        jlbGrid.add(lblCriarConta);
        lblCriarConta.setBounds(990, 280, 190, 17);

        chkManterLogin.setFont(new java.awt.Font("Lato", 0, 20)); // NOI18N
        chkManterLogin.setForeground(new java.awt.Color(0, 0, 0));
        chkManterLogin.setText("Manter login");
        chkManterLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkManterLoginActionPerformed(evt);
            }
        });
        jlbGrid.add(chkManterLogin);
        chkManterLogin.setBounds(740, 520, 150, 29);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/seta_avancar.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jlbGrid.add(jButton1);
        jButton1.setBounds(1100, 570, 80, 50);

        txtPswdInput.setBackground(new java.awt.Color(255, 255, 255));
        txtPswdInput.setForeground(new java.awt.Color(0, 0, 0));
        jlbGrid.add(txtPswdInput);
        txtPswdInput.setBounds(740, 430, 440, 50);

        jblBackground.add(jlbGrid);
        jlbGrid.setBounds(30, 160, 1320, 650);

        getContentPane().add(jblBackground);
        jblBackground.setBounds(0, 0, 1920, 1010);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chkManterLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkManterLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkManterLoginActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        String user = txtUserInput.getText();
        String pwd = new String(txtPswdInput.getPassword());
        
        boolean logado = LoginService.autenticar( user, pwd);
        
        if (logado) {
            JOptionPane.showMessageDialog(this, "✅ Login realizado com sucesso!");
            this.dispose();
            new TelaGerenciarRestaurante().setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "❌ Usuário e/ou senha incorretos.");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void lblCriarContaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCriarContaMouseClicked
        // TODO add your handling code here:
        
        this.dispose();
        
        TelaCadastro cadastro = new TelaCadastro();
        cadastro.setVisible(true);
    }//GEN-LAST:event_lblCriarContaMouseClicked

    private void lblEsqueceuSenhaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEsqueceuSenhaMouseClicked
        // TODO add your handling code here:
        
        this.dispose(); //fecha a tela atual
        
        TelaResetSenha resetsenha = new TelaResetSenha();
        resetsenha.setVisible(true);
    }//GEN-LAST:event_lblEsqueceuSenhaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaLoginNew().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox chkManterLogin;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jblBackground;
    private javax.swing.JPanel jlbGrid;
    private javax.swing.JLabel lblCriarConta;
    private javax.swing.JLabel lblEsqueceuSenha;
    private javax.swing.JPasswordField txtPswdInput;
    private javax.swing.JTextField txtUserInput;
    // End of variables declaration//GEN-END:variables
}
