/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.nearfood.views;

import br.com.nearfood.models.Usuario;
import br.com.nearfood.service.UsuarioService;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author firmodev
 */
public class TelaCadastro extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaCadastro.class.getName());

    /**
     * Creates new form TelaCadastro
     */
    public TelaCadastro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        JpnlFundo = new javax.swing.JPanel();
        jPnlBoxcadastro = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboTipoUsuario = new javax.swing.JComboBox<>();
        txtEmail = new javax.swing.JTextField();
        txtTelefone = new javax.swing.JTextField();
        txtConfirmaSenha = new javax.swing.JPasswordField();
        txtSenha = new javax.swing.JPasswordField();
        btnCadastrarUser = new javax.swing.JButton();
        txtLastName = new javax.swing.JTextField();
        txtFirstName = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(186, 139, 84));
        setPreferredSize(new java.awt.Dimension(1050, 800));

        JpnlFundo.setBackground(new java.awt.Color(186, 139, 84));
        JpnlFundo.setPreferredSize(new java.awt.Dimension(1049, 900));
        JpnlFundo.setLayout(new java.awt.GridBagLayout());

        jPnlBoxcadastro.setLayout(null);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Imagem__tela-cadastro.png"))); // NOI18N
        jLabel4.setText("jLabel4");
        jPnlBoxcadastro.add(jLabel4);
        jLabel4.setBounds(0, 0, 480, 700);

        jLabel2.setFont(new java.awt.Font("Poppins SemiBold", 0, 14)); // NOI18N
        jLabel2.setText("Conclua agora seu cadastro e venha fazer parte do Nearfood!");
        jPnlBoxcadastro.add(jLabel2);
        jLabel2.setBounds(500, 10, 470, 30);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logos/traced-logo-nearfood.png.png"))); // NOI18N
        jPnlBoxcadastro.add(jLabel3);
        jLabel3.setBounds(670, 60, 90, 100);

        jComboTipoUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CLIENTE", "ADIMINISTRADOR", " " }));
        jComboTipoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboTipoUsuarioActionPerformed(evt);
            }
        });
        jPnlBoxcadastro.add(jComboTipoUsuario);
        jComboTipoUsuario.setBounds(520, 190, 150, 23);

        txtEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtEmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtEmailFocusLost(evt);
            }
        });
        jPnlBoxcadastro.add(txtEmail);
        txtEmail.setBounds(520, 320, 420, 40);
        jPnlBoxcadastro.add(txtTelefone);
        txtTelefone.setBounds(520, 370, 420, 40);

        txtConfirmaSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtConfirmaSenhaActionPerformed(evt);
            }
        });
        jPnlBoxcadastro.add(txtConfirmaSenha);
        txtConfirmaSenha.setBounds(520, 470, 420, 40);
        jPnlBoxcadastro.add(txtSenha);
        txtSenha.setBounds(520, 420, 420, 40);

        btnCadastrarUser.setBackground(new java.awt.Color(255, 126, 34));
        btnCadastrarUser.setFont(new java.awt.Font("Fira Sans", 0, 18)); // NOI18N
        btnCadastrarUser.setText("CADASTRAR-SE");
        btnCadastrarUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarUserActionPerformed(evt);
            }
        });
        jPnlBoxcadastro.add(btnCadastrarUser);
        btnCadastrarUser.setBounds(650, 570, 160, 40);

        txtLastName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtLastNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtLastNameFocusLost(evt);
            }
        });
        jPnlBoxcadastro.add(txtLastName);
        txtLastName.setBounds(520, 270, 420, 40);

        txtFirstName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtFirstNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFirstNameFocusLost(evt);
            }
        });
        jPnlBoxcadastro.add(txtFirstName);
        txtFirstName.setBounds(520, 220, 420, 40);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 979;
        gridBagConstraints.ipady = 699;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(70, 30, 50, 40);
        JpnlFundo.add(jPnlBoxcadastro, gridBagConstraints);

        getContentPane().add(JpnlFundo, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarUserActionPerformed
        String firstName = txtFirstName.getText();
        String lastname = txtLastName.getText();       
        String password = new String(txtSenha.getPassword());
        String email = txtEmail.getText();
        String tipo_usuario = "cliente"; // ou pegue de um comboBox
        String telefone = txtTelefone.getText();

        Usuario usuario = new Usuario(nome, password, email, tipo_usuario, telefone);

        boolean sucesso = UsuarioService.cadastrarUsuario(usuario);

        if (sucesso) {
            JOptionPane.showMessageDialog(this, "Usuário cadastrado com sucesso!");
            
            telaLogin login = new telaLogin();
            login.setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Erro ao cadastrar usuário. Verifique a API.");
        }

    }//GEN-LAST:event_btnCadastrarUserActionPerformed

    private void txtEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusGained
        // TODO add your handling code here:
         if (txtEmail.getText().equals("Insira seu nome completo")) {
            
            txtEmail.setText("");
            txtEmail.setForeground(new Color(153, 153, 153));
            
        }
    }//GEN-LAST:event_txtEmailFocusGained

    private void txtEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusLost
        // TODO add your handling code here:
         if (txtEmail.getText().equals("")) {
            
            txtEmail.setText("Insira seu nome completo");
            txtEmail.setForeground(new Color(153, 153, 153));
            
        }
    }//GEN-LAST:event_txtEmailFocusLost

    private void jComboTipoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboTipoUsuarioActionPerformed
        // aqui o usuario escolhera se o cadatro sera de um cliente ou admin (ou seja, dono de restaurante)
        // caso o valor escolhido seja cliente, o campo CNPJ fica desabilitado ou desaparece. se não o campo CNPJ fica obrigatorio
        
    }//GEN-LAST:event_jComboTipoUsuarioActionPerformed

    private void txtConfirmaSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtConfirmaSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtConfirmaSenhaActionPerformed

    private void txtLastNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtLastNameFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLastNameFocusGained

    private void txtLastNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtLastNameFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLastNameFocusLost

    private void txtFirstNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFirstNameFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFirstNameFocusGained

    private void txtFirstNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFirstNameFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFirstNameFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaCadastro().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JpnlFundo;
    private javax.swing.JButton btnCadastrarUser;
    private javax.swing.JComboBox<String> jComboTipoUsuario;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPnlBoxcadastro;
    private javax.swing.JPasswordField txtConfirmaSenha;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JPasswordField txtSenha;
    private javax.swing.JTextField txtTelefone;
    // End of variables declaration//GEN-END:variables
}
