/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.nearfood.views;

import br.com.nearfood.service.LoginService;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author firmodev
 */
public class telaLogin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(telaLogin.class.getName());

    /**
     * Creates new form telaLogin1
     */
    public telaLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblNaoTemConta = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        esqueceuSenha = new javax.swing.JLabel();
        chkManterLogin = new javax.swing.JCheckBox();
        btnAvancar = new javax.swing.JButton();
        txtPassword = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Imagem-login.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logos/Logo Nearfood__extenso.png"))); // NOI18N
        getContentPane().add(jLabel2);

        jLabel3.setFont(new java.awt.Font("Poppins Medium", 0, 26)); // NOI18N
        jLabel3.setText("Olá, seja muito bem-vindo ao");
        getContentPane().add(jLabel3);

        lblNaoTemConta.setFont(new java.awt.Font("Lato", 1, 15)); // NOI18N
        lblNaoTemConta.setText("Não tem login? Crie sua conta");
        lblNaoTemConta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblNaoTemConta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNaoTemContaMouseClicked(evt);
            }
        });
        getContentPane().add(lblNaoTemConta);

        txtEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtEmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtEmailFocusLost(evt);
            }
        });
        getContentPane().add(txtEmail);

        esqueceuSenha.setFont(new java.awt.Font("Lato", 1, 15)); // NOI18N
        esqueceuSenha.setText("Esqueceu sua senha?");
        esqueceuSenha.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        esqueceuSenha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                esqueceuSenhaMouseClicked(evt);
            }
        });
        getContentPane().add(esqueceuSenha);

        chkManterLogin.setFont(new java.awt.Font("Lato", 0, 13)); // NOI18N
        chkManterLogin.setText("Manter Login");
        chkManterLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(chkManterLogin);

        btnAvancar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/seta_avancar.png"))); // NOI18N
        btnAvancar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvancarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAvancar);

        txtPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPasswordFocusLost(evt);
            }
        });
        getContentPane().add(txtPassword);

        jLabel6.setFont(new java.awt.Font("Poppins Light", 0, 13)); // NOI18N
        jLabel6.setText("CONSULTE AQUI A");
        getContentPane().add(jLabel6);

        jLabel7.setFont(new java.awt.Font("Poppins Light", 0, 13)); // NOI18N
        jLabel7.setText("E OS");
        getContentPane().add(jLabel7);

        jLabel8.setFont(new java.awt.Font("Poppins Light", 0, 13)); // NOI18N
        jLabel8.setText("<HTML><U>POLÍTICA DE PRIVACIDADE</U> </HTML>");
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jLabel8);

        jLabel9.setFont(new java.awt.Font("Poppins Light", 0, 13)); // NOI18N
        jLabel9.setText("<html><u>TERMOS DE USO</u></html>");
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jLabel9);

        jLabel4.setFont(new java.awt.Font("Fira Sans", 0, 18)); // NOI18N
        jLabel4.setText("Email");
        getContentPane().add(jLabel4);

        jLabel5.setFont(new java.awt.Font("Fira Sans", 0, 18)); // NOI18N
        jLabel5.setText("Senha");
        getContentPane().add(jLabel5);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAvancarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvancarActionPerformed
        // TODO add your handling code here:
        String email = txtEmail.getText();
        String password = new String(txtPassword.getPassword());
        
        boolean logado = LoginService.autenticar(email, password);
        
        if (logado) {
            JOptionPane.showMessageDialog(this, "✅ Login realizado com sucesso!");
            this.dispose();
            new TelaGerenciarRestaurante().setVisible(true);
        }else {
            JOptionPane.showMessageDialog(this, "❌ Usuário ou senha incorretos.");
        }
    }//GEN-LAST:event_btnAvancarActionPerformed

    private void txtEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusGained
        
        if (txtEmail.getText().equals("Insira seu email")) {
            
            txtEmail.setText("");
            txtEmail.setForeground(new Color(153, 153, 153));
            
        }
    }//GEN-LAST:event_txtEmailFocusGained

    private void txtEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusLost
        // TODO add your handling code here:
         if (txtEmail.getText().equals("")) {
            
            txtEmail.setText("Insira seu email");
            txtEmail.setForeground(new Color(153, 153, 153));
            
        }
    }//GEN-LAST:event_txtEmailFocusLost

    private void lblNaoTemContaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNaoTemContaMouseClicked
        // TODO add your handling code here:
        
        this.dispose();
        
        TelaCadastro telaCadastro = new TelaCadastro();
        telaCadastro.setVisible(true);
    }//GEN-LAST:event_lblNaoTemContaMouseClicked

    private void esqueceuSenhaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_esqueceuSenhaMouseClicked
        // TODO add your handling code here:
        // tela esqueceu sua senha
        this.dispose();
        
        TelaResetSenha resetSenha = new TelaResetSenha();
        resetSenha.setVisible(true);
        
    }//GEN-LAST:event_esqueceuSenhaMouseClicked

    private void txtPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPasswordFocusGained
        if (txtPassword.getText().equals("Insira sua senha")) {
            
            txtPassword.setText("");
            txtPassword.setForeground(new Color(153, 153, 153));
            
        }
    }//GEN-LAST:event_txtPasswordFocusGained

    private void txtPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPasswordFocusLost
         if (txtPassword.getText().equals("")) {
            
            txtPassword.setText("Insira sua senha");
            txtPassword.setForeground(new Color(153, 153, 153));
            
        }
    }//GEN-LAST:event_txtPasswordFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new telaLogin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAvancar;
    private javax.swing.JCheckBox chkManterLogin;
    private javax.swing.JLabel esqueceuSenha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblNaoTemConta;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JPasswordField txtPassword;
    // End of variables declaration//GEN-END:variables
}
